#!/bin/sh -e
# Test driver for observe
driver=`readlink -f "$0"`
testdir=`dirname "$driver"`

[ -x run ]

PROCLOG="`pwd`/actual"
export PROCLOG

rule="$testdir/record-all"

[ -f rule ] && rule=./rule

"$testdir/../main" "$rule" ./run
