#!/usr/bin/env bash
# observe -- a process invocation observer
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2007-01-19
set -e

OBSERVE=`readlink -f "$0"`
OBSERVE_ROOT=`dirname "$OBSERVE"`
: ${OBSERVE_DRIVER:=default}
PATH="$OBSERVE_ROOT/$OBSERVE_DRIVER:$OBSERVE_ROOT:$PATH"

while getopts "v" o; do
    case "$o" in
        v)
        version; exit
        ;;
    esac
done
shift $(($OPTIND - 1))

# show usage
if [ $# -lt 1 ]; then
    usage
    exit
fi

OBSERVE_RULE=$1; shift
if ! [ -f "$OBSERVE_RULE" -a -r "$OBSERVE_RULE" ]; then
    usage
    false
fi

OBSERVE_LEVEL=$((${OBSERVE_LEVEL:-0} + 1))
OBSERVE_HOOKS=`mktemp -d /tmp/observe.XXXXXX`
trap "rm -rf $OBSERVE_HOOKS >&2" EXIT

export OBSERVE_ROOT OBSERVE_LEVEL OBSERVE_RULE OBSERVE_HOOKS

# compile OBSERVE_RULE to OBSERVE_HOOKS
compile "$OBSERVE_RULE" "$OBSERVE_HOOKS"

if type begin &>/dev/null; then
    # run in an instrumented environment
    cmd=${1:-$SHELL}; shift
    name=`basename "$cmd"`
    begin "$cmd" "$name" "$@"
else
    echo "$OBSERVE_DRIVER: driver unavailable" >&2
fi
