#!/bin/sh
cat <<EOF
Observe `cat "$OBSERVE_ROOT/version.number"`
Copyright (C) 2007-2008 Jaeho Shin and others.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Type \`observe -vv' for details.

System: `cat "$OBSERVE_ROOT/version.system"`

Drivers:
`cat "$OBSERVE_ROOT/version.drivers"`

EOF
