#!/bin/sh -e

OBSERVE_CAPTURE_SO="$OBSERVE_ROOT/drivers/libc/capture.so"
export OBSERVE_CAPTURE_SO

# we need capture.so
[ -x "$OBSERVE_CAPTURE_SO" ]

# and run given command
exec "$OBSERVE_ROOT/handle" "$@"
