#!/usr/bin/env bash

OBSERVE_HOOKS_EXES="$OBSERVE_HOOKS/exes"
export OBSERVE_HOOKS_EXES

# create $OBSERVE_HOOKS_EXES
mkdir -p "$OBSERVE_HOOKS_EXES"
while read; do
    case "$REPLY" in
        # read a hook rule
        "hook "*)
        cmds=$REPLY
        cmds=${cmds#hook }
        cmds=${cmds%:*}
        # place an hook executable
        # TODO use hardlinks
        for cmd in $cmds; do
            [ "$cmd" != handle ] || continue
            cp -pf "$OBSERVE_ROOT/path.win32/escape.exe" "$OBSERVE_HOOKS_EXES/$cmd"
        done
        ;;
    esac
done <"$OBSERVE_RULE"

# and run given command
exec handle "$@"
