#!/bin/sh

OBSERVE_HOOKS_EXES="$OBSERVE_HOOKS/exes"
mkdir -p "$OBSERVE_HOOKS_EXES"

# generate hook dir from $OBSERVE_RULE
cat "$OBSERVE_RULE" |
while read; do
    case "$REPLY" in
        # read a hook rule
        "hook "*)
        cmds=$REPLY
        cmds=${cmds#hook }
        cmds=${cmds%:*}
        # place an hook executable
        # TODO use hardlinks
        for cmd in $cmds; do
            [ "$cmd" != handle ] || continue
            cp -pf "$OBSERVE_ROOT/path.win32/hook.exe" "$OBSERVE_HOOKS_EXES/$cmd"
        done
        ;;
    esac
done
