#!/bin/sh

if hook=`"$OBSERVE_HOOKS/match" "$1" "$2"`; then
    # hook found, let it handle
    handler="$OBSERVE_HOOKS/$hook"
else
    # no matching hook, release and run it
# TODO: consider using asolute path
    handler="$OBSERVE_DRIVER_ROOT/release"
fi

exec "$handler" "$@"
